# SITE CONFIGURATION
baseurl: ""
url: "https://omprabhu31.github.io/"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Om Prabhu
  subtitle: also this is not animé
  avatar: assets/img/bruh.JPG
  favicon: favicon.ico
  description: "My Blog"

#  Header and footer text
  header_text: >
     <p><h1>Home</h1></p>
  header_text_feature_image: assets/img/sample_feature_img.png
  footer_text: >
   © 2021. All lefts reserved · Powered by <a href="https://pages.github.com/">Github Pages</a> and <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/rohanchandra/type-theme/">Type Theme</a>
   <center><a href="https://forms.gle/d12hiHhnEpvDcL2u7">Anonymous message</a></center>

  # Icons
  email_address: omp3108@gmail.com
  facebook: 
  instagram: 
  linkedin:  https://www.linkedin.com/in/omprabhu31
  github: "omprabhu31"
  reddit: 
  stack_exchange: 
  steam: 
  youtube: 

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup
  search: false # Enable the search feature

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."
  str_search_no_results: "No results found."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: 
  - jekyll-paginate
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
